version: '3'
services:
  mysql:
    image: mysql:latest
    env_file:
      - ./.env
      - ./.env.development.local
  keycloak:
    image: jboss/keycloak
    env_file:
      - ./.env
      - ./.env.development.local
    ports:
      - "8080:8080"
